In [1]:
import pandas as pd

from pythonlatex.pandas_to_latex import PandasTable
from pythonlatex.highlight_formatter import HighlightFormatter
from tests.test_pandas import highlight_format

In [2]:
df = pd.read_csv("ressources/mol_results_example.csv", index_col=0).reset_index(drop=True)
df

,embedder,dataset,val_AUROC,n_samples,balanced,val_R2,val_Spearman,task_type,category,short_name
0,ChemBertMTR-77M,AMES,0.876124,7278.0,0.046029,NaN,NaN,cls,Tox,AMES
1,ChemBertMTR-77M,BBB Martins,0.920755,2030.0,0.264039,NaN,NaN,cls,Distribution,BBB
2,ChemBertMTR-77M,Bioavailability Ma,0.621104,640.0,0.268750,NaN,NaN,cls,Absorption,Bioavailability
3,ChemBertMTR-77M,CYP2C9 Substrate CarbonMangels,0.677036,669.0,0.289238,NaN,NaN,cls,Metabolism,CYP2C9 (s)
4,ChemBertMTR-77M,CYP2C9 Veith,0.891681,12092.0,0.165481,NaN,NaN,cls,Metabolism,CYP2C9
...,...,...,...,...,...,...,...,...,...,...
1753,MolR tag,LD50 Zhu,NaN,7385.0,0.958667,0.519262,0.698991,reg,Tox,LD50
1754,MolR tag,LD50 Zhu,NaN,7385.0,0.958667,0.516357,0.696717,reg,Tox,LD50
1755,MolR tag,LD50 Zhu,NaN,7385.0,0.958667,0.516514,0.690714,reg,Tox,LD50
1756,MolR tag,LD50 Zhu,NaN,7385.0,0.958667,0.513684,0.693524,reg,Tox,LD50
1757,MolR tag,LD50 Zhu,NaN,7385.0,0.958667,0.531945,0.700792,reg,Tox,LD50

# Example 1
We will create a table with the following features:

- We highlight the maximum values in the table
- We underline and bold the maximum values, bold the second maximum values

In [3]:
formatter = HighlightFormatter(
    highlight_method = "max", # What values need to be highlighted (max, min, or a custom function)
    highlight_format = ["\\textbf{\\underline{", "\\textbf{"] # How to format the highlighted values bold, underlined, etc.
)

table = PandasTable(
    df,  # Dataframe to convert to format
    higlighter = formatter, # HighlightFormatter object or a string if "max" or "min", will bold the max or min values
    n_decimals = 3, # Number of decimals to keep in the table
    rotate = "", # Whether to rotate the name of the columns
    add_std = True, # Whether to add the standard deviation of the values
    multicols = None, # Whether to add multi-columns (see below for more details)
)

In [4]:
table["embedder", "dataset", "val_AUROC"]

,\shortstack{AMES},\shortstack{BBB Martins},\shortstack{Bioavailability Ma},\shortstack{CYP2C9 Substrate CarbonMangels},\shortstack{CYP2C9 Veith},\shortstack{Carcinogens Lagunin},\shortstack{ClinTox},\shortstack{DILI},\shortstack{HIA Hou},\shortstack{PAMPA NCATS},\shortstack{Pgp Broccatelli},\shortstack{Skin Reaction},\shortstack{hERG (k)},\shortstack{hERG},\shortstack{avg}
GraphMVP,0.847,0.881,0.61,0.617,0.856,0.82,0.599,0.894,\textbf{0.885},0.676,0.879,0.731,0.854,0.76,0.779
MolR tag,\textbf{0.863},0.88,\textbf{\underline{0.65}},0.633,\textbf{0.885},0.79,\textbf{\underline{0.785}},0.878,0.873,0.702,0.935,0.694,\textbf{0.866},0.785,0.801
ThreeDInfomax,0.861,\textbf{0.903},0.608,\textbf{0.664},0.875,\textbf{0.861},\textbf{0.769},\textbf{0.896},0.867,\textbf{\underline{0.74}},\textbf{0.941},\textbf{0.763},0.86,\textbf{0.788},\textbf{0.814}
ChemBertMTR-77M,\textbf{\underline{0.876}},\textbf{\underline{0.921}},\textbf{0.621},\textbf{\underline{0.677}},\textbf{\underline{0.892}},\textbf{\underline{0.862}},0.676,\textbf{\underline{0.902}},\textbf{\underline{0.908}},\textbf{0.739},\textbf{\underline{0.944}},\textbf{\underline{0.783}},\textbf{\underline{0.883}},\textbf{\underline{0.857}},\textbf{\underline{0.824}}

In [5]:
table["dataset", "embedder", "val_AUROC"]

,\shortstack{ChemBertMTR-77M},\shortstack{GraphMVP},\shortstack{MolR tag},\shortstack{ThreeDInfomax},\shortstack{avg}
Bioavailability Ma,0.621,0.61,0.65,0.608,0.622
CYP2C9 Substrate CarbonMangels,0.677,0.617,0.633,0.664,0.648
PAMPA NCATS,0.739,0.676,0.702,0.74,0.714
ClinTox,0.676,0.599,0.785,0.769,0.707
Skin Reaction,0.783,0.731,0.694,0.763,0.743
hERG,0.857,0.76,0.785,0.788,0.797
Carcinogens Lagunin,0.862,0.82,0.79,0.861,0.833
AMES,0.876,0.847,0.863,0.861,0.862
hERG (k),0.883,0.854,0.866,0.86,0.866
CYP2C9 Veith,0.892,0.856,\textbf{0.885},0.875,0.877
DILI,0.902,\textbf{\underline{0.894}},0.878,0.896,0.892
HIA Hou,0.908,\textbf{0.885},0.873,0.867,0.883
BBB Martins,\textbf{0.921},0.881,0.88,\textbf{0.903},\textbf{0.896}
Pgp Broccatelli,\textbf{\underline{0.944}},0.879,\textbf{\underline{0.935}},\textbf{\underline{0.941}},\textbf{\underline{0.925}}

In [6]:
table["embedder", "category", "val_AUROC"]

,\shortstack{Absorption},\shortstack{Distribution},\shortstack{Metabolism},\shortstack{Tox},\shortstack{avg}
GraphMVP,0.764,0.881,0.737,0.786,0.792
MolR tag,\textbf{0.79},0.88,0.759,0.808,0.809
ThreeDInfomax,0.789,\textbf{0.903},\textbf{0.769},\textbf{0.828},\textbf{0.822}
ChemBertMTR-77M,\textbf{\underline{0.803}},\textbf{\underline{0.921}},\textbf{\underline{0.784}},\textbf{\underline{0.834}},\textbf{\underline{0.836}}

In [7]:
table.latex

'\\begin{tabular}{r||c|c|c|c|c|}\n{} & {\\shortstack{Absorption}} & {\\shortstack{Distribution}} & {\\shortstack{Metabolism}} & {\\shortstack{Tox}} & {\\shortstack{avg}} \\\\\nGraphMVP & 0.764 & 0.881 & 0.737 & 0.786 & 0.792 \\\\\nMolR tag & \\textbf{0.79} & 0.88 & 0.759 & 0.808 & 0.809 \\\\\nThreeDInfomax & 0.789 & \\textbf{0.903} & \\textbf{0.769} & \\textbf{0.828} & \\textbf{0.822} \\\\\nChemBertMTR-77M & \\textbf{\\underline{0.803}} & \\textbf{\\underline{0.921}} & \\textbf{\\underline{0.784}} & \\textbf{\\underline{0.834}} & \\textbf{\\underline{0.836}} \\\\\n\\end{tabular}\n'

# Example 2
We will create a table with the following features:

- We highlight the maximum values in the table
- We underline and bold the maximum values, bold the second maximum values
- The category of the task will be added at the top

In [8]:
# We specify the multi-columns to be added, we want for each dataset, the category, and the dataset name
multicols = {
    dataset: [df[df["dataset"] == dataset]["category"].unique()[0], dataset] for dataset in df["dataset"].unique()
}
multicols

{'AMES': ['Tox', 'AMES'],
 'BBB Martins': ['Distribution', 'BBB Martins'],
 'Bioavailability Ma': ['Absorption', 'Bioavailability Ma'],
 'CYP2C9 Substrate CarbonMangels': ['Metabolism',
  'CYP2C9 Substrate CarbonMangels'],
 'CYP2C9 Veith': ['Metabolism', 'CYP2C9 Veith'],
 'Caco2 Wang': ['Absorption', 'Caco2 Wang'],
 'Carcinogens Lagunin': ['Tox', 'Carcinogens Lagunin'],
 'ClinTox': ['Tox', 'ClinTox'],
 'DILI': ['Tox', 'DILI'],
 'HIA Hou': ['Absorption', 'HIA Hou'],
 'HydrationFreeEnergy FreeSolv': ['Absorption',
  'HydrationFreeEnergy FreeSolv'],
 'LD50 Zhu': ['Tox', 'LD50 Zhu'],
 'Lipophilicity (az)': ['Absorption', 'Lipophilicity (az)'],
 'PAMPA NCATS': ['Absorption', 'PAMPA NCATS'],
 'PPBR AZ': ['Distribution', 'PPBR AZ'],
 'Pgp Broccatelli': ['Absorption', 'Pgp Broccatelli'],
 'Skin  Reaction': ['Tox', 'Skin  Reaction'],
 'Solubility AqSolDB': ['Absorption', 'Solubility AqSolDB'],
 'VDss Lombardo': ['Distribution', 'VDss Lombardo'],
 'hERG': ['Tox', 'hERG'],
 'hERG (k)': ['Tox', 'hERG (k)']}

In [9]:
formatter = HighlightFormatter(
    highlight_method = "max", # What values need to be highlighted (max, min, or a custom function)
    highlight_format = ["\\textbf{\\underline{", "\\textbf{"] # How to format the highlighted values bold, underlined, etc.
)
table = PandasTable(
    df,  # Dataframe to convert to format
    higlighter = formatter, # HighlightFormatter object or a string if "max" or "min", will bold the max or min values
    n_decimals = 3, # Number of decimals to keep in the table
    rotate = "", # Whether to rotate the name of the columns
    add_std = True, # Whether to add the standard deviation of the values
    multicols = multicols, # Whether to add multi-columns (see below for more details)
)

In [10]:
table["embedder", "dataset", "val_AUROC"]

,\shortstack{\\avg},\shortstack{Absorption\\Bioavailability Ma},\shortstack{Absorption\\HIA Hou},\shortstack{Absorption\\PAMPA NCATS},\shortstack{Absorption\\Pgp Broccatelli},\shortstack{Distribution\\BBB Martins},\shortstack{Metabolism\\CYP2C9 Substrate CarbonMangels},\shortstack{Metabolism\\CYP2C9 Veith},\shortstack{Tox\\AMES},\shortstack{Tox\\Carcinogens Lagunin},\shortstack{Tox\\ClinTox},\shortstack{Tox\\DILI},\shortstack{Tox\\Skin Reaction},\shortstack{Tox\\hERG (k)},\shortstack{Tox\\hERG}
GraphMVP,0.779,0.61,\textbf{0.885},0.676,0.879,0.881,0.617,0.856,0.847,0.82,0.599,0.894,0.731,0.854,0.76
MolR tag,0.801,\textbf{\underline{0.65}},0.873,0.702,0.935,0.88,0.633,\textbf{0.885},\textbf{0.863},0.79,\textbf{\underline{0.785}},0.878,0.694,\textbf{0.866},0.785
ThreeDInfomax,\textbf{0.814},0.608,0.867,\textbf{\underline{0.74}},\textbf{0.941},\textbf{0.903},\textbf{0.664},0.875,0.861,\textbf{0.861},\textbf{0.769},\textbf{0.896},\textbf{0.763},0.86,\textbf{0.788}
ChemBertMTR-77M,\textbf{\underline{0.824}},\textbf{0.621},\textbf{\underline{0.908}},\textbf{0.739},\textbf{\underline{0.944}},\textbf{\underline{0.921}},\textbf{\underline{0.677}},\textbf{\underline{0.892}},\textbf{\underline{0.876}},\textbf{\underline{0.862}},0.676,\textbf{\underline{0.902}},\textbf{\underline{0.783}},\textbf{\underline{0.883}},\textbf{\underline{0.857}}

In [11]:
table.save_latex("ressources/mol_results_example.tex")

![Resulting Table](ressources/latex_table.png)